# Generated by Django 3.2.8 on 2022-04-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ListEvenment', '0008_auto_20220428_1850'),
        ('person', '0003_auto_20220428_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_CommandEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evenment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ListEvenment.evenment')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
            ],
        ),
    ]
