# Generated by Django 3.2.8 on 2022-04-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commendEvent', '0002_rename_evenment_list_commandevent_listevenment'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_commandevent',
            name='porte',
            field=models.CharField(choices=[('national', 'national'), ('international', 'international'), ('wilaya', 'wilaya'), ('interwilaya', 'interwilaya')], max_length=100, null=True),
        ),
    ]
