# Generated by Django 3.2.8 on 2022-05-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ListEvenment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('ListEvenment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ListEvenment.evenment')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
