# Generated by Django 3.2.8 on 2022-04-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0007_rename_forme_juridique_evenment_organisateur'),
        ('person', '0002_remove_person_prenom'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ListEvenment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ListEvenment.evenment'),
        ),
        migrations.AddField(
            model_name='data',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
    ]
