# Generated by Django 3.2.8 on 2022-05-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0007_alter_evenment_country'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ListEvenment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ListEvenment.evenment'),
        ),
    ]
