# Generated by Django 3.2.8 on 2022-04-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20220418_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='ListEvenment',
        ),
        migrations.RemoveField(
            model_name='data',
            name='person',
        ),
    ]
