# Generated by Django 3.2.8 on 2022-04-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20220428_1850'),
        ('ListEvenment', '0010_evenment_country'),
        ('map', '0003_auto_20220428_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ListEvenment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ListEvenment.evenment'),
        ),
        migrations.AddField(
            model_name='data',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
    ]
