# Generated by Django 3.2.8 on 2022-04-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20220428_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='ListEvenment',
        ),
        migrations.RemoveField(
            model_name='data',
            name='person',
        ),
    ]
