# Generated by Django 3.2.8 on 2022-05-23 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomevenment', models.CharField(max_length=100, null=True)),
                ('porte', models.CharField(choices=[('national', 'national'), ('international', 'international'), ('wilaya', 'wilaya'), ('interwilaya', 'interwilaya')], max_length=100, null=True)),
                ('type_evenment', models.CharField(choices=[('culturel', 'culturel'), ('sport', 'sport'), ('religieux', 'religieux'), ('scientifiques', 'scientifiques')], max_length=100, null=True)),
                ('Adresse_deEvent', models.CharField(max_length=100, null=True)),
                ('Email_Intervenant', models.CharField(max_length=100, null=True)),
                ('organisateur', models.CharField(choices=[('SARL', 'SARL'), ('EURL', 'EURL'), ('AMBASSADE', 'AMBASSADE'), ('ASSOCIATION', 'ASSOCIATION'), ('FEDERATION', 'FEDERATION'), ('MINISTERE', 'MINISTERE'), ('ARTISAN', 'ARTISAN'), ('CHAMBRE', 'CHAMBRE'), ('SPA', 'SPA')], max_length=100, null=True)),
                ('Descriptinos', models.TextField(null=True)),
                ('date_creation_evenment', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fine_evenment', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Acountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.data')),
            ],
            options={
                'verbose_name': 'Evenment',
                'verbose_name_plural': 'Evenment',
                'ordering': ('-date_creation_evenment',),
            },
        ),
    ]
