# Generated by Django 3.2.8 on 2022-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evenment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomevenment', models.CharField(max_length=100, null=True)),
                ('poerte', models.CharField(choices=[('national', 'national'), ('international', 'international'), ('wilaya', 'wilaya'), ('interwilaya', 'interwilaya')], max_length=100, null=True)),
                ('type_evenment', models.CharField(choices=[('culturel', 'culturel'), ('sport', 'sport'), ('religieux', 'religieux'), ('scientifiques', 'scientifiques')], max_length=100, null=True)),
                ('Adresse', models.CharField(max_length=100, null=True)),
                ('Télephone', models.CharField(max_length=100, null=True)),
                ('Email_Intervenant', models.CharField(max_length=100, null=True)),
                ('Forme_juridique', models.CharField(choices=[('SARL', 'SARL'), ('EURL', 'international'), ('AMBASSADE', 'AMBASSADE'), ('ASSOCIATION', 'ASSOCIATION'), ('FEDERATION', 'FEDERATION'), ('MINISTERE', 'MINISTERE'), ('ARTISAN', 'ARTISAN'), ('CHAMBRE', 'CHAMBRE'), ('SPA', 'SPA')], max_length=100, null=True)),
            ],
        ),
    ]
