# Generated by Django 3.2.8 on 2022-04-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenment',
            old_name='poerte',
            new_name='porte',
        ),
    ]
