# Generated by Django 3.2.8 on 2022-05-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenment',
            options={'verbose_name': 'Evenment', 'verbose_name_plural': 'Evenment'},
        ),
        migrations.AddField(
            model_name='evenment',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
