# Generated by Django 3.2.8 on 2022-06-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('ListEvenment', '0002_alter_evenment_acountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenment',
            name='Acountry',
        ),
        migrations.AddField(
            model_name='evenment',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.data'),
        ),
    ]
