# Generated by Django 3.2.8 on 2022-04-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0002_rename_poerte_evenment_porte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenment',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='evenment',
            name='Email_Intervenant',
        ),
        migrations.RemoveField(
            model_name='evenment',
            name='Forme_juridique',
        ),
        migrations.RemoveField(
            model_name='evenment',
            name='Télephone',
        ),
    ]
