# Generated by Django 3.2.8 on 2022-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0002_auto_20220504_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenment',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
