# Generated by Django 3.2.8 on 2022-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0003_auto_20220418_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenment',
            name='Adresse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
