# Generated by Django 3.2.8 on 2022-05-04 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0004_alter_evenment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenment',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
