# Generated by Django 3.2.8 on 2022-06-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0004_rename_country_evenment_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenment',
            name='ville',
        ),
    ]
