# Generated by Django 3.2.8 on 2022-04-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0005_auto_20220418_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenment',
            name='Forme_juridique',
            field=models.CharField(choices=[('SARL', 'SARL'), ('EURL', 'EURL'), ('AMBASSADE', 'AMBASSADE'), ('ASSOCIATION', 'ASSOCIATION'), ('FEDERATION', 'FEDERATION'), ('MINISTERE', 'MINISTERE'), ('ARTISAN', 'ARTISAN'), ('CHAMBRE', 'CHAMBRE'), ('SPA', 'SPA')], max_length=100, null=True),
        ),
    ]
