# Generated by Django 3.2.8 on 2022-04-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0006_alter_evenment_forme_juridique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenment',
            old_name='Forme_juridique',
            new_name='organisateur',
        ),
    ]
