# Generated by Django 3.2.8 on 2022-04-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0008_auto_20220428_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenment',
            old_name='Adresse',
            new_name='Adresse_deEvent',
        ),
        migrations.RenameField(
            model_name='evenment',
            old_name='body',
            new_name='Descriptinos',
        ),
        migrations.RenameField(
            model_name='evenment',
            old_name='Télephone',
            new_name='Email_Intervenant',
        ),
    ]
