# Generated by Django 3.2.8 on 2022-05-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0008_auto_20220505_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenment',
            options={'ordering': ('-date_creation_evenment',), 'verbose_name': 'Evenment', 'verbose_name_plural': 'Evenment'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('Comment_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('Evenment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ListEvenment.evenment')),
            ],
        ),
    ]
