# Generated by Django 3.2.8 on 2022-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0009_auto_20220505_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-Comment_date',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=50),
        ),
    ]
