# Generated by Django 3.2.8 on 2022-04-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0010_evenment_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenment',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
