# Generated by Django 3.2.8 on 2022-04-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListEvenment', '0011_evenment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenment',
            name='image',
        ),
    ]
